[".local/share/fonts/CascadiaCodeNF"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/CascadiaCode.tar.xz"
	exact = true
	include = ["**/*.ttf", "**/*.ttc"]

[".local/share/fonts/IosevkaNF"]
	type = "archive"
	url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Iosevka.tar.xz"
	exact = true
	include = ["**/*.ttf", "**/*.ttc"]
