### COMMON SHELL CONFIG ###

aliases:
  g: git
  cm: chezmoi
  vi: nvim
  vim: nvim
  fetch: neofetch --config ~/.config/neofetch/simple.conf

env:
  EDITOR: nvim
  PAGER: less -R

### COLOR SCHEME ###

colors:
  background:    &background    '#1d1f21'
  foreground:    &foreground    '#c5c8c6'
  black:         &black         '#282a2e'
  red:           &red           '#a54242'
  green:         &green         '#8c9440'
  yellow:        &yellow        '#de935f'
  blue:          &blue          '#5f819d'
  magenta:       &magenta       '#85678f'
  cyan:          &cyan          '#5e8d87'
  white:         &white         '#707880'
  brightBlack:   &brightBlack   '#373b41'
  brightRed:     &brightRed     '#cc6666'
  brightGreen:   &brightGreen   '#b5bd68'
  brightYellow:  &brightYellow  '#f0c674'
  brightBlue:    &brightBlue    '#81a2be'
  brightMagenta: &brightMagenta '#b294bb'
  brightCyan:    &brightCyan    '#8abeb7'
  brightWhite:   &brightWhite   '#c5c8c6'

color:
  - *black
  - *red
  - *green
  - *yellow
  - *blue
  - *magenta
  - *cyan
  - *white
  - *brightBlack
  - *brightRed
  - *brightGreen
  - *brightYellow
  - *brightBlue
  - *brightMagenta
  - *brightCyan
  - *brightWhite

### STARSHIP HELPER VARS ###

battery:
  symbols:
    10: ["󰂃","󰢟"]
    20: ["󰁺","󰢜"]
    30: ["󰁻","󰂆"]
    40: ["󰁼","󰂇"]
    50: ["󰁽","󰂈"]
    60: ["󰁾","󰢝"]
    70: ["󰁿","󰂉"]
    80: ["󰂀","󰢞"]
    90: ["󰂁","󰂊"]
    99: ["󰂂","󰂋"]
  colors:
    - red
    - yellow
    - bright-yellow
    - green
    - bright-green

### LOCAL BIN HELPER VARS ###

bin:
  starship:
    arch:
      arm64: aarch64
      arm: arm
      386: i686
      amd64: x86_64
    os:
      darwin: apple-darwin
      windows: pc-windows-msvc
      linux: unknown-linux-gnu
      android: unknown-linux-musl
