colors:
  background:    &background '#1d1f21'
  foreground:    &foreground '#c5c8c6'
  black:         &color0     '#282a2e'
  red:           &color1     '#a54242'
  green:         &color2     '#8c9440'
  yellow:        &color3     '#de935f'
  blue:          &color4     '#5f819d'
  magenta:       &color5     '#85678f'
  cyan:          &color6     '#5e8d87'
  white:         &color7     '#707880'
  brightBlack:   &color8     '#373b41'
  brightRed:     &color9     '#cc6666'
  brightGreen:   &color10    '#b5bd68'
  brightYellow:  &color11    '#f0c674'
  brightBlue:    &color12    '#81a2be'
  brightMagenta: &color13    '#b294bb'
  brightCyan:    &color14    '#8abeb7'
  brightWhite:   &color15    '#c5c8c6'
color:
  - *color0
  - *color1
  - *color2
  - *color3
  - *color4
  - *color5
  - *color6
  - *color7
  - *color8
  - *color9
  - *color10
  - *color11
  - *color12
  - *color13
  - *color14
  - *color15

aliases:
  g: git
  cm: chezmoi
  vi: nvim
  vim: nvim

env:
  EDITOR: nvim
  PAGER: less -R

battery:
  symbols:
    10: ["󰂃","󰢟"]
    20: ["󰁺","󰢜"]
    30: ["󰁻","󰂆"]
    40: ["󰁼","󰂇"]
    50: ["󰁽","󰂈"]
    60: ["󰁾","󰢝"]
    70: ["󰁿","󰂉"]
    80: ["󰂀","󰢞"]
    90: ["󰂁","󰂊"]
    99: ["󰂂","󰂋"]
  colors:
    - red
    - yellow
    - bright-yellow
    - green
    - bright-green

starship:
  arch:
    arm64: aarch64
    arm: arm
    386: i686
    amd64: x86_64
  os:
    darwin: apple-darwin
    windows: pc-windows-msvc
    linux: unknown-linux-gnu
    android: unknown-linux-musl
