colors:
  background:    '#1d1f21'
  foreground:    '#c5c8c6'
  black:         &color0  '#282a2e'
  red:           &color1  '#a54242'
  green:         &color2  '#8c9440'
  yellow:        &color3  '#de935f'
  blue:          &color4  '#5f819d'
  magenta:       &color5  '#85678f'
  cyan:          &color6  '#5e8d87'
  white:         &color7  '#707880'
  brightBlack:   &color8  '#373b41'
  brightRed:     &color9  '#cc6666'
  brightGreen:   &color10 '#b5bd68'
  brightYellow:  &color11 '#f0c674'
  brightBlue:    &color12 '#81a2be'
  brightMagenta: &color13 '#b294bb'
  brightCyan:    &color14 '#8abeb7'
  brightWhite:   &color15 '#c5c8c6'
  color0:        *color0
  color1:        *color1
  color2:        *color2
  color3:        *color3
  color4:        *color4
  color5:        *color5
  color6:        *color6
  color7:        *color7
  color8:        *color8
  color9:        *color9
  color10:       *color10
  color11:       *color11
  color12:       *color12
  color13:       *color13
  color14:       *color14
  color15:       *color15
