local plugins = {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "commonlisp",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "dot",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "hcl",
      "html",
      "http",
      "ini",
      "java",
      "javascript",
      "jq",
      "json",
      "lua",
      "make",
      "markdown_inline",
      "matlab",
      "passwd",
      "perl",
      "php",
      "python",
      "r",
      "regex",
      "ruby",
      "rust",
      "scss",
      "terraform",
      "todotxt",
      "toml",
      "typescript",
      "vhs",
      "vim",
      "yaml"
    }
  }
}

return plugins
